project:
  name: quickstart-quantiphi-lex-kendra-backend
  owner: sarvesh.virkud@quantiphi.com
  package_lambda: false
  lambda_zip_path: ./functions/packages/
  regions:
    - eu-west-1
    - us-west-2
    - us-east-1
tests:
  quickstart-quantiphi:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      KendraS3BucketName: $[taskcat_autobucket]
      KendraFAQFileKey: quickstart-quantiphi-lex-kendra-backend/assets/FAQ-document/COVID_FAQ.csv
      LexBotJSONKey: quickstart-quantiphi-lex-kendra-backend/assets/lex-bot-template/covid_bot_Export.json
    template: ./templates/lex_bot_kendra_master.template